name: C/C++ CI

on:
  push:
  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile C++ Code
      run: g++ -o main Contoh.cpp

    - name: Run Program
      run: ./main
